import Head from "next/head";
import { Header } from "@/components/header/index.jsx";
import About from "@/components/about";
import Projects from "@/components/projects";
import Contacts from "@/components/contacts";
import Icons from "@/sections/icons";
export default function Home() {
  return (
    <>
      <Head>
        <title>Anas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <Projects />
      <Contacts />
      <Icons />
    </>
  );
}
